### ISSUE TITLE
Providing singularity images

### ISSUE THREAD

**Issue by ryanmboileau** [zhongw2/GeneTEFlow#4]
Hello,

If possible would you be able to add to the repository the pipeline's converted singularity container file? My colleagues and I are unable to convert docker images with our current HPC set up. 

Looking forward to trying this! 
Thank you kindly,
Ryan

**Comment by Davidxcliu** [comment]
Dear Ryan,

Thanks for your interest in GeneTEFlow! 
However, I could not add the singularity images into GitHub repository due to the file size limitation. After converting docker images to singularity images, each singularity image is ~2.2Gb on average, and total four singularity images are ~8.8Gb.

Alternatively, I am providing you temporarily the download links for these singularity images on Google Drive (15 days, by 6/20):

**Process image:** https://drive.google.com/file/d/1zGqX9_p2JGdwZg5UG_DW2SBgT23Cc0SG/view?usp=sharing
**Analysis image:** https://drive.google.com/file/d/1SQY9aF_rqDbRU08fnWEzg4Yj76kr9zfv/view?usp=sharing
**SampleInfo image:** https://drive.google.com/file/d/13CRw-K4O6KcEIvNHIMxsSth-Zm-Ei7pc/view?usp=sharing
**TE analysis image:** https://drive.google.com/file/d/1yee95JaF65WZp8Q9WQhL7-pbqvZb2P7B/view?usp=sharing

At the end, I would recommend you that it would be best to install your docker and singularity locally so that you could convert them at your convenience.

Hope these singularity images are helpful for your projects.
Thanks!
